// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(ApplicationUserId), Name = "UI_ApplicationUserSubscriptionPlan", IsUnique = true)]
    public partial class ApplicationUserSubscriptionPlan
    {
        [Key]
        [Column("ApplicationUserSubscriptionPlan")]
        public long ApplicationUserSubscriptionPlan1 { get; set; }
        public long ApplicationUserId { get; set; }
        public short SubscriptionPlanId { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("ApplicationUserSubscriptionPlan")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(SubscriptionPlanId))]
        [InverseProperty("ApplicationUserSubscriptionPlan")]
        public virtual SubscriptionPlan SubscriptionPlan { get; set; }
    }
}