// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(ApplicationUserId), nameof(GatedFeatureId), Name = "UI_ApplicationUserFeature_", IsUnique = true)]
    public partial class ApplicationUserFeature
    {
        [Key]
        public long ApplicationUserFeatureId { get; set; }
        public long ApplicationUserId { get; set; }
        public int GatedFeatureId { get; set; }
        public bool Enabled { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("ApplicationUserFeature")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(GatedFeatureId))]
        [InverseProperty("ApplicationUserFeature")]
        public virtual GatedFeature GatedFeature { get; set; }
    }
}