// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(Name), Name = "UI_Brand_Name", IsUnique = true)]
    public partial class Brand
    {
        public Brand()
        {
            BrandVideo = new HashSet<BrandVideo>();
        }

        [Key]
        public long BrandId { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [Required]
        [StringLength(500)]
        public string Description { get; set; }
        public long ApplicationUserId { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("Brand")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [InverseProperty("Brand")]
        public virtual ICollection<BrandVideo> BrandVideo { get; set; }
    }
}