// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(SenderBatchId), Name = "UI_PaypalPayoutBatch_SenderBatchId", IsUnique = true)]
    public partial class PaypalPayoutBatch
    {
        public PaypalPayoutBatch()
        {
            PaypalPayoutBatchItem = new HashSet<PaypalPayoutBatchItem>();
        }

        [Key]
        public long PaypalPayoutBatchId { get; set; }
        public Guid PayoutBatchId { get; set; }
        public Guid SenderBatchId { get; set; }
        [Required]
        [StringLength(250)]
        public string EmailSubject { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string EmailMessage { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [InverseProperty("PaypalPayoutBatch")]
        public virtual ICollection<PaypalPayoutBatchItem> PaypalPayoutBatchItem { get; set; }
    }
}