// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    public partial class PaypalPayoutBatchItem
    {
        [Key]
        public long PaypalPayoutBatchItemId { get; set; }
        public long PaypalPayoutBatchId { get; set; }
        [Required]
        [StringLength(50)]
        public string RecipientType { get; set; }
        [Column(TypeName = "money")]
        public decimal AmountValue { get; set; }
        [Required]
        [StringLength(50)]
        public string AmountCurrency { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string Note { get; set; }
        public Guid SenderItemId { get; set; }
        [Required]
        [StringLength(150)]
        public string ReceiverEmailAddress { get; set; }
        [Required]
        [StringLength(50)]
        public string NotificationLanguage { get; set; }

        [ForeignKey(nameof(PaypalPayoutBatchId))]
        [InverseProperty("PaypalPayoutBatchItem")]
        public virtual PaypalPayoutBatch PaypalPayoutBatch { get; set; }
    }
}