// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(OrderId), Name = "UI_PaypalTransaction_OrderId", IsUnique = true)]
    public partial class PaypalTransaction
    {
        [Key]
        public long PaypalTransactionId { get; set; }
        [Required]
        [StringLength(50)]
        public string OrderId { get; set; }
        [Column(TypeName = "money")]
        public decimal OrderAmount { get; set; }
        public long ApplicationUserId { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("PaypalTransaction")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}