// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    public partial class RoleRequest
    {
        [Key]
        public long RoleRequestId { get; set; }
        public long ApplicationUserId { get; set; }
        public long RequestedApplicationRoleId { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [Required]
        [StringLength(150)]
        public string Lastname { get; set; }
        [Required]
        [StringLength(150)]
        public string Surname { get; set; }
        [Required]
        [StringLength(100)]
        public string Nationality { get; set; }
        public int NationalId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime BirthDate { get; set; }
        [Required]
        [StringLength(200)]
        public string RequestReason { get; set; }
        public bool IsApproved { get; set; }

        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }

        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        public DateTimeOffset RowCreationDateTime { get; set; }

        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("RoleRequest")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}