// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(Name), Name = "UI_SubscriptionPlan_Name", IsUnique = true)]
    public partial class SubscriptionPlan
    {
        public SubscriptionPlan()
        {
            ApplicationUserSubscriptionPlan = new HashSet<ApplicationUserSubscriptionPlan>();
        }

        [Key]
        public short SubscriptionPlanId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(250)]
        public string Description { get; set; }
        public short? MaxAllowedWeeklyVideos { get; set; }

        [InverseProperty("SubscriptionPlan")]
        public virtual ICollection<ApplicationUserSubscriptionPlan> ApplicationUserSubscriptionPlan { get; set; }
    }
}