// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(ApplicationUserId), Name = "UI_[UserVideoRating_ApplicationUserId", IsUnique = true)]
    [Index(nameof(VideoInfoId), Name = "UI_[UserVideoRating_VideoInfoId", IsUnique = true)]
    public partial class UserVideoRating
    {
        [Key]
        public long UserVideoRatingId { get; set; }
        public long ApplicationUserId { get; set; }
        public long VideoInfoId { get; set; }
        public byte Rating { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserVideoRating")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(VideoInfoId))]
        [InverseProperty("UserVideoRating")]
        public virtual VideoInfo VideoInfo { get; set; }
    }
}