// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(ApplicationUserId), nameof(YouTubeChannelId), Name = "UI_UserYouTubeChannel_UserYouTubeChannel", IsUnique = true)]
    public partial class UserYouTubeChannel
    {
        [Key]
        public long UserYouTubeChannelId { get; set; }
        public long ApplicationUserId { get; set; }
        [Required]
        [StringLength(50)]
        public string YouTubeChannelId { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserYouTubeChannel")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}