// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    public partial class UserFollower
    {
        [Key]
        public long UserFollowerId { get; set; }
        public long FollowedApplicationUserId { get; set; }
        public long FollowerApplicationUserId { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [ForeignKey(nameof(FollowedApplicationUserId))]
        [InverseProperty(nameof(ApplicationUser.UserFollowerFollowedApplicationUser))]
        public virtual ApplicationUser FollowedApplicationUser { get; set; }
        [ForeignKey(nameof(FollowerApplicationUserId))]
        [InverseProperty(nameof(ApplicationUser.UserFollowerFollowerApplicationUser))]
        public virtual ApplicationUser FollowerApplicationUser { get; set; }
    }
}