// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(Name), Name = "UI_UserRequestType_Name", IsUnique = true)]
    public partial class UserRequestType
    {
        [Key]
        public short UserRequestTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
    }
}