// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    public partial class UserVerificationStatus
    {
        public UserVerificationStatus()
        {
            UserProfile = new HashSet<UserProfile>();
        }

        [Key]
        public long UserVerificationStatusId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(200)]
        public string Description { get; set; }

        [InverseProperty("UserVerificationStatus")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}