// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(Name), Name = "UI_UserRequestType_Name", IsUnique = true)]
    public partial class UserRequestType
    {
        public UserRequestType()
        {
            UserRequest = new HashSet<UserRequest>();
        }

        [Key]
        public short UserRequestTypeId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("UserRequestType")]
        public virtual ICollection<UserRequest> UserRequest { get; set; }
    }
}