// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    public partial class VideoIndexStatus
    {
        public VideoIndexStatus()
        {
            VideoInfo = new HashSet<VideoInfo>();
        }

        [Key]
        public short VideoIndexStatusId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("VideoIndexStatus")]
        public virtual ICollection<VideoInfo> VideoInfo { get; set; }
    }
}