// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    public partial class VideoVisibility
    {
        public VideoVisibility()
        {
            VideoInfo = new HashSet<VideoInfo>();
        }

        [Key]
        public short VideoVisibilityId { get; set; }
        [Required]
        [StringLength(10)]
        public string Name { get; set; }

        [InverseProperty("VideoVisibility")]
        public virtual ICollection<VideoInfo> VideoInfo { get; set; }
    }
}