// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(VideoInfoId), nameof(Keyword), Name = "UI_VideoIndexKeyword_Keyword", IsUnique = true)]
    public partial class VideoIndexKeyword
    {
        [Key]
        public long VideoIndexKwywordId { get; set; }
        public long VideoInfoId { get; set; }
        [Required]
        [StringLength(500)]
        public string Keyword { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [ForeignKey(nameof(VideoInfoId))]
        [InverseProperty("VideoIndexKeyword")]
        public virtual VideoInfo VideoInfo { get; set; }
    }
}