// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    [Index(nameof(VideoCommentId), Name = "UI_VideoCommentAnalysis_VideoCommentId", IsUnique = true)]
    public partial class VideoCommentAnalysis
    {
        [Key]
        [Column("VideoCommentAnalysis")]
        public long VideoCommentAnalysis1 { get; set; }
        public long VideoCommentId { get; set; }
        [Required]
        [StringLength(50)]
        public string Sentiment { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string KeyPhrases { get; set; }

        [ForeignKey(nameof(VideoCommentId))]
        [InverseProperty("VideoCommentAnalysis")]
        public virtual VideoComment VideoComment { get; set; }
    }
}