// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayTube.DataAccess.Models
{
    public partial class VideoJobApplication
    {
        [Key]
        public long VideoJobApplicationId { get; set; }
        public long VideoJobId { get; set; }
        public long ApplicantApplicationUserId { get; set; }
        [Required]
        [Column(TypeName = "text")]
        public string ApplicantCoverLetter { get; set; }
        public short VideoJobApplicationStatusId { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [ForeignKey(nameof(ApplicantApplicationUserId))]
        [InverseProperty(nameof(ApplicationUser.VideoJobApplication))]
        public virtual ApplicationUser ApplicantApplicationUser { get; set; }
        [ForeignKey(nameof(VideoJobId))]
        [InverseProperty("VideoJobApplication")]
        public virtual VideoJob VideoJob { get; set; }
        [ForeignKey(nameof(VideoJobApplicationStatusId))]
        [InverseProperty("VideoJobApplication")]
        public virtual VideoJobApplicationStatus VideoJobApplicationStatus { get; set; }
    }
}