// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayTube.DataAccess.Models
{
    public partial class VideoInfo
    {
        public VideoInfo()
        {
            BrandVideo = new HashSet<BrandVideo>();
            VideoAccessTransaction = new HashSet<VideoAccessTransaction>();
            VideoComment = new HashSet<VideoComment>();
            VideoIndexKeyword = new HashSet<VideoIndexKeyword>();
            VideoIndexingTransaction = new HashSet<VideoIndexingTransaction>();
            VideoJob = new HashSet<VideoJob>();
            VideoJobApplication = new HashSet<VideoJobApplication>();
        }

        [Key]
        public long VideoInfoId { get; set; }
        public Guid AccountId { get; set; }
        [StringLength(50)]
        public string VideoId { get; set; }
        [Required]
        [StringLength(50)]
        public string Location { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(500)]
        public string Description { get; set; }
        [Required]
        [StringLength(50)]
        public string FileName { get; set; }
        [Required]
        [StringLength(500)]
        public string VideoBloblUrl { get; set; }
        [StringLength(500)]
        public string IndexedVideoUrl { get; set; }
        /// <summary>
        /// Video Owner Id
        /// </summary>
        public long ApplicationUserId { get; set; }
        public short VideoIndexStatusId { get; set; }
        public double VideoDurationInSeconds { get; set; }
        [StringLength(500)]
        public string VideoIndexSourceClass { get; set; }
        [Column(TypeName = "money")]
        public decimal Price { get; set; }
        [StringLength(500)]
        public string ExternalVideoSourceUrl { get; set; }
        [StringLength(10)]
        public string VideoLanguageCode { get; set; }
        public short VideoVisibilityId { get; set; }
        [StringLength(500)]
        public string ThumbnailUrl { get; set; }
        public DateTimeOffset RowCreationDateTime { get; set; }
        [Required]
        [StringLength(256)]
        public string RowCreationUser { get; set; }
        [Required]
        [StringLength(250)]
        public string SourceApplication { get; set; }
        [Required]
        [Column("OriginatorIPAddress")]
        [StringLength(100)]
        public string OriginatorIpaddress { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("VideoInfo")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(VideoIndexStatusId))]
        [InverseProperty("VideoInfo")]
        public virtual VideoIndexStatus VideoIndexStatus { get; set; }
        [ForeignKey(nameof(VideoVisibilityId))]
        [InverseProperty("VideoInfo")]
        public virtual VideoVisibility VideoVisibility { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual UserVideoRating UserVideoRating { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual ICollection<BrandVideo> BrandVideo { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual ICollection<VideoAccessTransaction> VideoAccessTransaction { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual ICollection<VideoComment> VideoComment { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual ICollection<VideoIndexKeyword> VideoIndexKeyword { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual ICollection<VideoIndexingTransaction> VideoIndexingTransaction { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual ICollection<VideoJob> VideoJob { get; set; }
        [InverseProperty("VideoInfo")]
        public virtual ICollection<VideoJobApplication> VideoJobApplication { get; set; }
    }
}