// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FairPlayTube.DataAccess.Models;

#nullable disable

namespace FairPlayTube.DataAccess.Data
{
    public partial class FairplaytubeDatabaseContext : DbContext
    {
        public FairplaytubeDatabaseContext()
        {
        }

        public FairplaytubeDatabaseContext(DbContextOptions<FairplaytubeDatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ApplicationRole> ApplicationRole { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUser { get; set; }
        public virtual DbSet<ApplicationUserRole> ApplicationUserRole { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<BrandVideo> BrandVideo { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<UserExternalMonetization> UserExternalMonetization { get; set; }
        public virtual DbSet<UserFeedback> UserFeedback { get; set; }
        public virtual DbSet<UserFollower> UserFollower { get; set; }
        public virtual DbSet<UserInvitation> UserInvitation { get; set; }
        public virtual DbSet<UserVideoRating> UserVideoRating { get; set; }
        public virtual DbSet<VideoIndexKeyword> VideoIndexKeyword { get; set; }
        public virtual DbSet<VideoIndexStatus> VideoIndexStatus { get; set; }
        public virtual DbSet<VideoInfo> VideoInfo { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=FairPlayTube.Database;Integrated Security=true");

            modelBuilder.Entity<ApplicationUserRole>(entity =>
            {
                entity.HasOne(d => d.ApplicationRole)
                    .WithMany(p => p.ApplicationUserRole)
                    .HasForeignKey(d => d.ApplicationRoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ApplicationUserRole_ApplicationRole");

                entity.HasOne(d => d.ApplicationUser)
                    .WithOne(p => p.ApplicationUserRole)
                    .HasForeignKey<ApplicationUserRole>(d => d.ApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ApplicationUserRole_ApplicationUser");
            });

            modelBuilder.Entity<Brand>(entity =>
            {
                entity.HasOne(d => d.ApplicationUser)
                    .WithMany(p => p.Brand)
                    .HasForeignKey(d => d.ApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Brand_ApplicationUserId");
            });

            modelBuilder.Entity<BrandVideo>(entity =>
            {
                entity.HasOne(d => d.Brand)
                    .WithMany(p => p.BrandVideo)
                    .HasForeignKey(d => d.BrandId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BrandVideo_Brand");

                entity.HasOne(d => d.VideoInfo)
                    .WithMany(p => p.BrandVideo)
                    .HasForeignKey(d => d.VideoInfoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BrandVideo_VideoInfo");
            });

            modelBuilder.Entity<UserExternalMonetization>(entity =>
            {
                entity.HasOne(d => d.ApplicationUser)
                    .WithMany(p => p.UserExternalMonetization)
                    .HasForeignKey(d => d.ApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserExternalMonetization_ApplicationUser");
            });

            modelBuilder.Entity<UserFeedback>(entity =>
            {
                entity.HasOne(d => d.ApplicationUser)
                    .WithMany(p => p.UserFeedback)
                    .HasForeignKey(d => d.ApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserFeedback_ApplicationUserId");
            });

            modelBuilder.Entity<UserFollower>(entity =>
            {
                entity.HasOne(d => d.FollowedApplicationUser)
                    .WithMany(p => p.UserFollowerFollowedApplicationUser)
                    .HasForeignKey(d => d.FollowedApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserFollower_FollowedApplicationUserId");

                entity.HasOne(d => d.FollowerApplicationUser)
                    .WithMany(p => p.UserFollowerFollowerApplicationUser)
                    .HasForeignKey(d => d.FollowerApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserFollower_FollowerApplicationUserId");
            });

            modelBuilder.Entity<UserInvitation>(entity =>
            {
                entity.HasOne(d => d.InvitingApplicationUser)
                    .WithMany(p => p.UserInvitation)
                    .HasForeignKey(d => d.InvitingApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserInvitation_InvitingApplicationUserId");
            });

            modelBuilder.Entity<UserVideoRating>(entity =>
            {
                entity.HasOne(d => d.ApplicationUser)
                    .WithOne(p => p.UserVideoRating)
                    .HasForeignKey<UserVideoRating>(d => d.ApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserVideoRating_ApplicationUserId");

                entity.HasOne(d => d.VideoInfo)
                    .WithOne(p => p.UserVideoRating)
                    .HasForeignKey<UserVideoRating>(d => d.VideoInfoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UserVideoRating_VideoInfoId");
            });

            modelBuilder.Entity<VideoIndexKeyword>(entity =>
            {
                entity.HasKey(e => e.VideoIndexKwywordId)
                    .HasName("PK_VideoIndex");

                entity.HasOne(d => d.VideoInfo)
                    .WithMany(p => p.VideoIndexKeyword)
                    .HasForeignKey(d => d.VideoInfoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_VideoIndexKeyword_VideoInfo");
            });

            modelBuilder.Entity<VideoInfo>(entity =>
            {
                entity.Property(e => e.ApplicationUserId).HasComment("Video Owner Id");

                entity.HasOne(d => d.ApplicationUser)
                    .WithMany(p => p.VideoInfo)
                    .HasForeignKey(d => d.ApplicationUserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_VideoInfo_ApplicationUser");

                entity.HasOne(d => d.VideoIndexStatus)
                    .WithMany(p => p.VideoInfo)
                    .HasForeignKey(d => d.VideoIndexStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_VideoInfo_VideoIndexStatus");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}